image:
 repository: chinedu10/complete-devops-project
<<<<<<< HEAD
 tag: "ea6e343"
=======
 tag: 9e7341e
>>>>>>> 7864637afead56332b0ce80fd3431668e53c810d
 pullPolicy: IfNotPresent
service:
 type: ClusterIP
 port: 8080
ingress:
 enabled: false
serviceAccount:
 enabled: false
autoscaling:
 enabled: false
httpRoute:
 enabled: false
 